### ISSUE TITLE
Not working with Rails 4

### ISSUE THREAD

**Issue by zedtux** [html5lib/html5lib-ruby#1]
After having added the gem in my Gemfile and ran `bundle`, when I'm restarting my app, I have the following error:

```
admin_1          | /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require': /bundle/gems/html5-0.10.0/lib/html5/inputstream.rb:305: too short escaped multibyte character: /^ (SyntaxError)
admin_1          |                 ( [\xC2-\xDF][\x80-\xBF]             # non-overlong 2-byte
admin_1          |                 |  \xE0[\xA0-\xBF][\x80-\xBF]        # excluding overlongs
admin_1          |                 | [\xE1-\xEC\xEE\xEF][\x80-\xBF]{2}  # straight 3-byte
admin_1          |                 |  \xED[\x80-\x9F][\x80-\xBF]        # excluding surrogates
admin_1          |                 |  \xF0[\x90-\xBF][\x80-\xBF]{2}     # planes 1-3
admin_1          |                 | [\xF1-\xF3][\x80-\xBF]{3}          # planes 4-15
admin_1          |                 |  \xF4[\x80-\x8F][\x80-\xBF]{2}     # plane 16
admin_1          |                 )/x
admin_1          | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
admin_1          | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
admin_1          | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
admin_1          | 	from /bundle/gems/html5-0.10.0/lib/html5/tokenizer.rb:2:in `<top (required)>'
admin_1          | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
admin_1          | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
admin_1          | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
admin_1          | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
admin_1          | 	from /bundle/gems/html5-0.10.0/lib/html5/html5parser.rb:2:in `<top (required)>'
admin_1          | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
admin_1          | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
admin_1          | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
admin_1          | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
admin_1          | 	from /bundle/gems/html5-0.10.0/lib/html5.rb:1:in `<top (required)>'
admin_1          | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
admin_1          | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
admin_1          | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
admin_1          | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
admin_1          | 	from /bundle/gems/xss_terminate-0.22/lib/xss_terminate.rb:2:in `<top (required)>'
admin_1          | 	from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler/runtime.rb:91:in `require'
admin_1          | 	from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
admin_1          | 	from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler/runtime.rb:86:in `each'
admin_1          | 	from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler/runtime.rb:86:in `block in require'
admin_1          | 	from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler/runtime.rb:75:in `each'
admin_1          | 	from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler/runtime.rb:75:in `require'
admin_1          | 	from /usr/local/bundle/gems/bundler-1.14.3/lib/bundler.rb:107:in `require'
admin_1          | 	from /application/config/application.rb:16:in `<top (required)>'
admin_1          | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:78:in `require'
admin_1          | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
admin_1          | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
admin_1          | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
admin_1          | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
admin_1          | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
admin_1          | 	from /application/bin/rails:9:in `require'
admin_1          | 	from /application/bin/rails:9:in `<top (required)>'
admin_1          | 	from /bundle/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
admin_1          | 	from /bundle/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
admin_1          | 	from /bundle/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
admin_1          | 	from /bundle/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
admin_1          | 	from /bundle/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
admin_1          | 	from /bundle/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
admin_1          | 	from /bundle/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
admin_1          | 	from /application/bin/spring:15:in `require'
admin_1          | 	from /application/bin/spring:15:in `<top (required)>'
admin_1          | 	from bin/rails:3:in `load'
admin_1          | 	from bin/rails:3:in `<main>'

```

**Comment by zedtux** [comment]
Apparently, repo no more maintained ... closing the issue.
